#!/bin/bash

echo "=========================================="
echo "设置 MySQL root 密码并创建数据库"
echo "=========================================="
echo ""

echo "由于 MySQL 已经有密码保护，请选择一个方案："
echo ""
echo "方案 1：交互式设置密码（推荐）"
echo "-----------------------------------"
echo "执行命令后，会提示输入当前密码（如果有的话）"
echo "如果不知道密码，请尝试空密码（直接按回车）"
echo ""
echo "步骤："
echo "  1. 执行：mysql -u root -p"
echo "  2. 输入当前密码（或直接回车尝试空密码）"
echo "  3. 在 MySQL> 提示符下执行："
echo "     ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123';"
echo "     CREATE DATABASE news_app CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
echo "     SHOW DATABASES;"
echo "     exit;"
echo ""
echo "=========================================="
echo ""
echo "方案 2：重置 MySQL root 密码（忘记密码时）"
echo "-----------------------------------"
echo "这需要停止 MySQL 并以安全模式启动"
echo ""
echo "执行以下命令："
echo ""
echo "# 1. 停止 MySQL"
echo "brew services stop mysql"
echo ""
echo "# 2. 以安全模式启动（跳过权限检查）"
echo "mysqld_safe --skip-grant-tables &"
echo ""
echo "# 3. 等待几秒"
echo "sleep 5"
echo ""
echo "# 4. 连接并重置密码"
echo "mysql -u root"
echo ""
echo "# 在 MySQL 命令行执行："
echo "FLUSH PRIVILEGES;"
echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123';"
echo "FLUSH PRIVILEGES;"
echo "exit;"
echo ""
echo "# 5. 停止安全模式"
echo "sudo killall mysqld"
echo ""
echo "# 6. 正常启动 MySQL"
echo "brew services start mysql"
echo ""
echo "# 7. 使用新密码连接"
echo "mysql -u root -proot123"
echo ""
echo "=========================================="
echo ""
echo "方案 3：尝试常见密码"
echo "-----------------------------------"
echo "尝试这些常见密码："
echo "  mysql -u root -p"
echo "  然后尝试: root, password, 123456, (空密码)"
echo ""
echo "=========================================="