#!/bin/bash

echo "=========================================="
echo "MySQL 切换指南"
echo "=========================================="
echo ""

# 检查当前运行的 MySQL
echo "当前运行的 MySQL 进程："
ps aux | grep mysqld | grep -v grep
echo ""

echo "=========================================="
echo "请按照以下步骤操作："
echo "=========================================="
echo ""
echo "步骤 1：停止旧的 MySQL（需要输入您的 macOS 用户密码）"
echo "------------------------------------------"
echo "执行命令："
echo "  sudo /usr/local/mysql/support-files/mysql.server stop"
echo ""
echo "如果提示 'ERROR! MySQL is not running', 说明已停止"
echo ""
echo "步骤 2：停止所有 Homebrew MySQL 服务"
echo "------------------------------------------"
echo "执行命令："
echo "  brew services stop mysql"
echo ""
echo "步骤 3：启动新的 Homebrew MySQL"
echo "------------------------------------------"
echo "执行命令："
echo "  brew services start mysql"
echo ""
echo "步骤 4：验证新 MySQL 正在运行"
echo "------------------------------------------"
echo "执行命令："
echo "  mysql --version"
echo ""
echo "应该显示：mysql  Ver 9.5.0 for macos26.1 on arm64 (Homebrew)"
echo ""
echo "步骤 5：创建数据库和设置密码"
echo "------------------------------------------"
echo "执行命令："
echo "  mysql -u root"
echo ""
echo "然后在 MySQL 命令行中执行："
echo "  ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123';"
echo "  CREATE DATABASE news_app CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
echo "  SHOW DATABASES;"
echo "  exit;"
echo ""
echo "=========================================="
echo "或者，一键执行所有步骤（如果已停止旧 MySQL）："
echo "=========================================="
echo "执行以下命令："
echo ""
echo "# 停止所有 MySQL"
echo "brew services stop mysql"
echo "sudo /usr/local/mysql/support-files/mysql.server stop 2>/dev/null"
echo ""
echo "# 启动新的 MySQL"
echo "brew services start mysql"
echo ""
echo "# 等待 3 秒让 MySQL 启动"
echo "sleep 3"
echo ""
echo "# 检查版本"
echo "mysql --version"
echo ""
echo "# 设置密码并创建数据库"
echo "mysql -u root -e \"ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123'; CREATE DATABASE news_app CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; SHOW DATABASES;\""
echo ""
echo "=========================================="